### ISSUE TITLE
Clarify what this is

### ISSUE THREAD

**Issue by 89z** [alecthomas/protobuf#26]
I see that this module is described as "A Protobuf parser for Go", but rather than parsing Protobuf wire format data, it appears to parse arbitrary `.proto` files. If I am right about this, I think it would be helpful to clarify that this package is used for parsing `.proto` files, rather than something else.

**Comment by alecthomas** [comment]
Good point, and in fact this is no longer a Protobuf parser at all! :)

**Comment by 89z** [comment]
Can you clarify? I am looking to parse the raw wire data. Can this do that?

**Comment by alecthomas** [comment]
No. Currently this can:

- Parse Protobuf IDL source files.
- Generate a FileDescriptorSet from those source files.

You probably want something in this package: https://pkg.go.dev/google.golang.org/protobuf@v1.27.1/encoding/protowire
